title: Your awesome title
email: your-email@example.com
description: >-
  Atomic Increment are a group of highly experienced coders who are
  passionate about code performance, Rust and saving you
  time and money when doing hard sums.

  We teach Rust in association with ferrous Systems, High Efficiency Computing
  and develop the "extendr" R extension system with help from the R ISC Comittee.
baseurl: ""
url: "" 
twitter_username: quaternioso
github_username:  andy-thomason

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
